### ISSUE TITLE
Prize on right side not displayed correctly

### ISSUE THREAD

**Issue by gsarahhhh** [BuildOnViction/bug-reports#83]
While browsing I noticed that the price for ADA/TOMO pair is not updating it only show the price of 0.12 wherever I clicked on the candle even if its dump or pump the price is the same unlike other pairs

![Untitled](https://user-images.githubusercontent.com/59993482/72960695-a8fc4200-3de9-11ea-8ead-d789816d8fe8.jpg)

you can see here if you point to the red candle it shows different price
![Untitled1](https://user-images.githubusercontent.com/59993482/72960783-ea8ced00-3de9-11ea-8b1c-7bd44b9bf11c.png)

**Comment by thanhvk** [comment]
This is because the precision of the price in charting fixed is 2. It's resolved at commit https://github.com/tomochain/tomox-sdk-ui/commit/444d3876f5ef8b87b811406770331ed892084c7a. 

The code is only available on devnet: 

![image](https://user-images.githubusercontent.com/11411161/73058009-47110a80-3ec5-11ea-8cc5-691ccfd5716b.png)

**Comment by thanhson1085** [comment]
Thank you. We fixed the issue before you reported it.
